stages:
  - test
  - code_analysis

# caching does not lead to a speed-up in our case - disabled
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - ./venv

before_script:
  - virtualenv --python py38 ./venv
  - source ./venv/bin/activate
  - pip3 install --upgrade pip
  - pip3 install -q -I -r requirements-dev.txt


unittests:
  stage: test
  script:
    - source ./venv/bin/activate
    - python3 -m unittest discover -v


black_check:
  stage: code_analysis
  script:
    - source ./venv/bin/activate
    - black --version
    - black ./crownetutils/ --fast --check --diff
  allow_failure: true
