"""Collection of classes and function to analyse and plot coupled simulations generated by CrowNet.

"""

from __future__ import annotations
from typing import Protocol

import pandas as pd


class RsdAssociationProvider(Protocol):
    def merge_rsd_id_on_host_time_interval(
        self,
        data: pd.DataFrame,
        host_id_col: str | int = "hostId",
        time_col="time",
        append_interval: bool = False,
    ) -> pd.DataFrame:
        """append ressource sharing domain (RSD) identifier to data frame.

        This methods uses the host_id and time to retrieve the assocation to a RSD.

        Args:
            data (pd.DataFrame): fram to which to append the rsd column
            host_id_col (str | int, optional): column or index name to use for host_id. Defaults to "hostId".
            time_col (str, optional): column or index name to use for time. Defaults to "time".
            append_interval (bool, optional): If true an pd.Interval column is added as well. Defaults to False.

        Returns:
            pd.DataFrame: _description_
        """
        ...